// <auto-generated />
using System;
using CScriptEz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CScriptEz.DataAccess.Migrations
{
    [DbContext(typeof(CScriptEzDbContext))]
    [Migration("20220217125321_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("CScriptEz.Data.Models.FileDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .HasColumnType("BLOB");

                    b.Property<int?>("FileModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileModelId");

                    b.ToTable("FilesData");
                });

            modelBuilder.Entity("CScriptEz.Data.Models.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("CScriptEz.Data.Models.FileDataModel", b =>
                {
                    b.HasOne("CScriptEz.Data.Models.FileModel", "FileModel")
                        .WithMany()
                        .HasForeignKey("FileModelId");

                    b.Navigation("FileModel");
                });
#pragma warning restore 612, 618
        }
    }
}
